[[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [ ".cache" ]

[build]
  functions = "netlify/functions"
  command = "node generate-headers.js && npm run build"

[[headers]]
  for = "/upload"
  [headers.values]
    Basic-Auth = "${BASIC_AUTH_USERNAME}:${BASIC_AUTH_PASSWORD}"