[[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [ ".cache" ]

[build]
  functions = "netlify/functions"

[[headers]]
  for = "/upload"
  [headers.values]
    X-Debug-Username = "${BASIC_AUTH_USERNAME}"
    X-Debug-Password = "${BASIC_AUTH_PASSWORD}"