[[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [ ".cache" ]

[build]
  functions = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    X-Debug-Test = "Netlify Is Reading Headers"


